companies/urls.py
from django.conf.urls import url
from . import views

app_name = 'companies'

urlpatterns = [

        # /companies/
        url(r'^$', views.IndexView.as_view(), name="index"),
        # /companies/contact/
        url(r'^contacts$', views.contacts, name="contacts"),
        # /companies/landViews/
        url(r'^services$', views.ServicesView.as_view(), name="services"),
        # /companies/landViews/
        url(r'^gallery$', views.GalleryView.as_view(), name="gallery"),
        # /companies/about_us/
        url(r'^aboutUs$', views.AboutUsView.as_view(), name="aboutUs"),

        url(r'^forms$', views.FormsView.as_view(), name="forms"),

]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^companies/', include('companies.urls', namespace="lands")),
]

companies/forms.py
from django import forms

# our new form
class ContactsForm(forms.Form):
    contact_name = forms.CharField(
        max_length=250,
        widget=forms.TextInput(attrs={'class': "form-control"}),)

    contact_email = forms.EmailField(
        max_length=250,
        widget=forms.TextInput(attrs={'class': "form-control"}),)

    contact_subject = forms.CharField(
        max_length=250,
        widget=forms.TextInput(attrs={'class': "form-control"}),)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'class': "form-control"})
    )

# the new bit we're adding
    def __init__(self, *args, **kwargs):
        super(ContactsForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = "Name:"
        self.fields['contact_email'].label = "E-mail:"
        self.fields['contact_subject'].label = "Subject:"
        self.fields['content'].label = "Message"

companies/views.py
from .forms import ContactsForm
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.template import Context
from django.template.loader import get_template
from django.views import generic
# Create your views here.

class IndexView(generic.TemplateView):
    template_name = 'companies/index.html'

class ServicesView(generic.TemplateView):
    template_name = 'companies/services.html'

class GalleryView(generic.TemplateView):
    template_name = 'companies/gallery.html'

class AboutUsView(generic.TemplateView):
    template_name = 'companies/aboutUs.html'

class ContactsView(generic.TemplateView):
    template_name = 'companies/contacts.html'

class FormsView(generic.TemplateView):
    template_name = 'companies/forms.html'



def contacts(request):
    form_class = ContactsForm
    # new logic!

    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get(
                'contact_name', '')
            contact_email = request.POST.get(
                'contact_email', '')
            contact_subject = request.POST.get(
                'contact_subject', '')
            form_content = request.POST.get('content', '')

            # Email the profile with the
            # contact information
            template = get_template("companies/contacts_template.text")
            context = Context({
                'contact_name': contact_name,
                'contact_email': contact_email,
                'contact_subject': contact_subject,
                'form_content': form_content,
            })
            content = template.render(context)

            email = EmailMessage(
                "New contact form submission",
                content,
                "Your website" + '',
                ['youremail@gmail.com'],
                headers={'Reply-To': contact_email}
            )
            email.send()
            return redirect('companies:index')

    return render(request, "companies/contacts.html", {'form': form_class, })

companies/templates/companies/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- META SECTION -->
        <title>{% block title %}Dolby Agency{% endblock %}</title>
        {% load staticfiles %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
            <!-- END META SECTION -->

        <link rel="icon" href="{% static 'companies/css/ka/vault/dol_icon.png' %}" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="{% static 'companies/css/revolution-slider/extralayers.css' %}" media="screen" />
        <link rel="stylesheet" type="text/css" href="{% static 'companies/css/revolution-slider/settings.css' %}" media="screen" />
        <link rel="stylesheet" type="text/css" href="{% static 'companies/css/bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'companies/css/styles.css' %}" media="screen" />

    </head>
    <body>
        <!-- page container -->
        <div class="page-container">

            <!-- page header -->
            <div class="page-header">

                <!-- page header holder -->
                <div class="page-header-holder">

                    <!-- page logo -->
                    <div class="logo">
                         <a href="{% url "companies:index" %}">Dolby Agency</a>



                    </div>
                    <!-- ./page logo -->


                    <!-- search -->
                    <div class="search">
                        <div class="search-button"><span class="fa fa-search"></span></div>
                        <div class="search-container animated fadeInDown">
                            <form action="#" method="post">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search..."/>
                                    <div class="input-group-btn">
                                        <button class="btn btn-primary"><span class="fa fa-search"></span></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- ./search -->

                    <!-- nav mobile bars -->
                    <div class="navigation-toggle">
                        <div class="navigation-toggle-button"><span class="fa fa-bars"></span></div>
                    </div>
                    <!-- ./nav mobile bars -->

                    <!-- navigation -->
                    <ul class="navigation">
                        <li>
                            <a href="{% url 'companies:index' %}">HOME</a>
                        </li>
                        <li>
                            <a href="{% url 'companies:services' %}">SERVICES</a>

                        </li>
                        <li>
                            <a href="{% url 'companies:aboutUs' %}">ABOUT US</a>
                        </li>
                        <li>
                            <a href="{% url "companies:contacts"%}">CONTACT US</a>

                        </li>
                    </ul>
                    <!-- ./navigation -->


                </div>
                <!-- ./page header holder -->

            </div>
            <!-- ./page header -->
            {% block body %}
            {% endblock %}

            <!-- page footer -->
            <div class="page-footer">

                <!-- page footer wrap -->
                <div class="page-footer-wrap bg-dark-gray">
                    <!-- page footer holder -->
                    <div class="page-footer-holder page-footer-holder-main">

                        <div class="row">

                            <!-- about -->
                            <div class="col-md-3">
                                <h3 style="color: orangered">ABOUT DOLBY AGENCY</h3>
                                <small  style="color: #3e74ff"><strong><i>Your Digital Marketing Partner</i></strong></small>
                                <p>
                                    Dolby Agency is a full service Digital Marketing and Media Agency that make<strong style="color: #3e74ff"> Memorable, Wow, Top of Mind</strong> marketing campaigns in the digital space.
                                </p>

                                <!-- social links -->
                                <div class="social-links">
                                    <ol>
                                        <a href="{% url 'companies:contacts' %}"><span class="fa fa-facebook"></span></a>
                                        <a href="{% url 'companies:contacts' %}"><span class="fa fa-twitter"></span></a>
                                        <a href="{% url 'companies:contacts' %}"><span class="fa fa-pinterest"></span></a>
                                        <a href="{% url 'companies:contacts' %}"><span class="fa fa-linkedin"></span></a>
                                        <a href="{% url 'companies:contacts' %}"><span class="fa fa-youtube"></span></a>
                                    </ol>

                                </div>
                            </div>
                            <!-- ./about
                             -->

                            <!-- quick links -->
                            <div class="col-md-3">
                                <h3>Quick links</h3>

                                <div class="list-links">
                                    <a href="{% url 'companies:index' %}">HOME</a>
                                    <a href="{% url 'companies:services' %}">SERVICES</a>
                                    <a href="{% url 'companies:aboutUs' %}">COMPANY</a>
                                    <a href="{% url 'companies:gallery' %}">GALLERY</a>
                                    <a href="{% url 'companies:contacts' %}">CONTACT US</a>
                                </div>
                            </div>
                            <!-- ./quick links -->

                            <!-- recent tweets -->
                            <div class="col-md-3">
                                <h3>LATEST NEWS</h3>

                                <div class="list-with-icon small">
                                    <div class="item">
                                        <div class="icon">
                                            <span class="fa fa-rss"></span>
                                        </div>
                                        <div class="text">
                                            <a href="{% url 'companies:services' %}">Email Marketing</a> - act of sending a commercial message, typically to a group of people, using email.
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="icon">
                                            <span class="fa fa-rss"></span>
                                        </div>
                                        <div class="text">
                                            <a href="{% url 'companies:services' %}">Targeted Demographics</a> - you can focus your marketing efforts on a specific market that is likely to buy from you.
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="icon">
                                            <span class="fa fa-rss"></span>
                                        </div>
                                        <div class="text">
                                            <a href="{% url 'companies:services' %}">Audio-Visual Content</a> - the use short clips to market your product in a more friendly way that is memorable.
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!-- ./recent tweets -->

                            <!-- contacts -->
                            <div class="col-md-3">
                                <h3>CONTACTS</h3>

                                <div class="footer-contacts">
                                    <div class="fc-row">
                                        <span class="fa fa-home"></span>
                                        7601-00100, Cathy Flats,<br/>
                                        Lenana Road, Nairobi,<br/>
                                        Kenya.
                                    </div>
                                    <div class="fc-row">
                                        <span class="fa fa-phone"></span>
                                        (+254) 713-614-056
                                    </div>
                                    <div class="fc-row">
                                        <span class="fa fa-envelope"></span>
                                        <strong>Dolby Agency</strong><br>
                                        <a href="{% url 'companies:contacts' %}">info@dolbyagency.com</a>
                                    </div>
                                    <div class="fc-row">
                                        <span class="fa fa-envelope"></span>
                                        <strong>Dolby Agency</strong><br>
                                        <a href="{% url 'companies:contacts' %}">brian@dolbyagency.com</a>
                                    </div>
                                </div>
                        <!-- ./social links -->

                            </div>
                            <!-- ./contacts -->

                        </div>

                    </div>
                    <!-- ./page footer holder -->
                </div>
                <!-- ./page footer wrap -->

                <!-- page footer wrap -->
                <div class="page-footer-wrap bg-darken-gray">
                    <!-- page footer holder -->
                    <div class="page-footer-holder">

                        <!-- copyright -->
                        <div class="copyright">
                            Dolby Agency &copy; 2017 by a2Z Solutions & Consultancy <a href="#">a2Z</a> | All Rights Reserved
                        </div>
                        <!-- ./copyright -->

                        <!-- social links -->
                        <div class="social-links">
                            <ol>
                                <a href="#"><span class="fa fa-facebook"></span></a>
                                <a href="#"><span class="fa fa-twitter"></span></a>
                                <a href="#"><span class="fa fa-pinterest"></span></a>
                                <a href="#"><span class="fa fa-linkedin"></span></a>
                                <a href="#"><span class="fa fa-youtube"></span></a>
                            </ol>

                        </div>

                    </div>
                    <!-- ./page footer holder -->
                </div>
                <!-- ./page footer wrap -->

            </div>
            <!-- ./page footer -->

        </div>
        <!-- ./page container -->

        <!-- page scripts -->
        <script type="text/javascript" src="{% static 'companies/js/plugins/jquery/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'companies/js/plugins/bootstrap/bootstrap.min.js' %}"></script>

        <script type="text/javascript" src="{% static 'companies/js/plugins/mixitup/jquery.mixitup.js' %}"></script>
        <script type="text/javascript" src="{% static 'companies/js/plugins/appear/jquery.appear.js' %}"></script>

        <script type="text/javascript" src="{% static 'companies/js/plugins/revolution-slider/jquery.themepunch.tools.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'companies/js/plugins/revolution-slider/jquery.themepunch.revolution.min.js' %}"></script>

        <script type="text/javascript" src="{% static 'companies/js/actions.js' %}"></script>
        <script type="text/javascript" src="{% static 'companies/js/slider.js' %}"></script>

        <!-- ./page scripts -->
    </body>
</html>

companies/templates/companies/contacts.html
{% extends 'companies/base.html' %}<!-- META SECTION -->
<html>
<head>
        {% block title %}Contact | Dolby Agency{% endblock %}
        {% load staticfiles %}
</head>
        {% block body %}
<body>
            <!-- page content -->
            <div class="page-content">

                <!-- page content wrapper -->
                <div class="page-content-wrap bg-light">
                    <!-- page content holder -->
                    <div class="page-content-holder no-padding">
                        <!-- page title -->
                        <div class="page-title">
                            <h1>Contact Us</h1>
                            <!-- breadcrumbs -->
                            <ul class="breadcrumb">
                                <li><a href="{% url 'companies:index' %}">Home</a></li>
                                <li><a href="{% url 'companies:services' %}">Services</a></li>
                                <li><a href="{% url 'companies:aboutUs' %}">About Us</a></li>
                                <li class="active">Contact Us</li>
                            </ul>
                            <!-- ./breadcrumbs -->
                        </div>
                        <!-- ./page title -->
                    </div>
                    <!-- ./page content holder -->
                </div>
                <!-- ./page content wrapper -->


                <!-- page content wrapper -->
                <div class="page-content-wrap">

                    <h3>Our Location</h3>

                    <div id="google-map" style="width: 100%; height: 300px;">

                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.808101527796!2d36.795446514274786!3d-1.289371185992034!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f10ba2f048315%3A0x740543505ed6491a!2sCathy+Flats%2C+Lenana+Rd%2C+Nairobi%2C+Kenya!5e0!3m2!1sen!2sca!4v1490979038067" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>

                    </div>

                </div>
                <!-- ./page content wrapper -->

                <!-- page content wrapper -->
                <div class="page-content-wrap">

                    <div class="divider">
                        <div class="box">
                            <span class="fa fa-angle-down"></span>
                        </div>
                    </div>

                    <!-- page content holder -->
                    <div class="page-content-holder">

                        <div class="row">
                            <div class="col-md-7 this-animate" data-animate="fadeInLeft">

                                <div class="text-column">
                                    <h4>Contact Us</h4>
                                    <div class="text-column-info">
                                        Talk to us we are always excited to hear from you!
                                    </div>
                                </div>

                                <div class="row">
                                    {{ form.non_field_errors }}
                                    <form class="form-group" action=""  method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% include 'companies/form-template.html' %}
                                     <div>
                                         <button type="submit" class="btn btn-primary btn-lg pull-right">Send Message</button>
                                     </div>
                                    </form>
                                </div>

                            </div>
                            <div class="col-md-5 this-animate" data-animate="fadeInRight">

                                <div class="text-column text-column-centralized">
                                    <div class="text-column-icon">
                                        <span class="fa fa-home"></span>
                                    </div>
                                    <h4>Our Office</h4>
                                    <div class="text-column-info">
                                        <p><strong><span class="fa fa-phone"></span> Phone: </strong> (+254) 713-614-056</p>
                                        <p><strong><span class="fa fa-envelope"></span> E-mail: </strong> <a href="#">info@dolbyagency.com</a></p>
                                        <p><strong><span class="fa fa-envelope"></span> E-mail: </strong> <a href="#">brian@dolbyagency.com</a></p>
                                        <p><strong><span class="fa fa-map-marker"></span> Address: </strong> 7601-00100, Cathy Flats, <br />Lenana Road, Nairobi, Kenya.</p>

                                    </div>
                                </div>

                                <div class="text-column text-column-centralized">
                                    <div class="text-column-icon">
                                        <span class="fa fa-clock-o"></span>
                                    </div>
                                    <h4>Working Hours</h4>
                                    <div class="text-column-info">
                                        <p><strong>Monday &mdash; Friday</strong>: 8:00am - 5:00pm</p>
                                        <p><strong>Saturday </strong>: 8:00am - 12:00noon</p>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                    <!-- ./page content holder -->
                </div>
                <!-- ./page content wrapper -->

            </div>
            <!-- ./page content -->
        {% endblock %}
</body>
</html>

companies/templates/companies/form-template.html
{% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}

companies/templates/companies/gallery.html
            <!-- META SECTION -->
            {% extends 'companies/base.html' %}
            {% block title %}Gallery | Dolby Agency{% endblock %}
            {% block body %}
            {% load staticfiles %}

                <!-- page content -->
                <div class="page-content">

                    <!-- page content wrapper -->
                    <div class="page-content-wrap bg-light">
                        <!-- page content holder -->
                        <div class="page-content-holder no-padding">
                            <!-- page title -->
                            <div class="page-title">
                                <h1>Gallery</h1>
                                <!-- breadcrumbs -->
                                <ul class="breadcrumb">
                                    <li><a href="{% url 'companies:index' %}">Home</a></li>
                                    <li><a href="{% url 'companies:services' %}">Services</a></li>
                                    <li><a href="{% url 'companies:aboutUs' %}">About Us</a></li>
                                    <li><a href="{% url 'companies:contacts' %}">Contact Us</a></li>
                                    <li class="active">Our Gallery</li>
                                </ul>
                                <!-- ./breadcrumbs -->
                            </div>
                            <!-- ./page title -->
                        </div>
                        <!-- ./page content holder -->
                    </div>
                    <!-- ./page content wrapper -->


                    <!-- page content wrapper -->
                <div class="page-content-wrap">
                    <!-- page content holder -->
                    <div class="page-content-holder">

                        <div class="block-heading this-animate" data-animate="fadeInDown">
                            <h2>OUR GALLERY: A bit of our work</h2>
                            <div class="block-heading-text">
                                Below is a preview of Dolby Agency's work with our clients.
                            </div>
                        </div>


                        <div class="row mix-grid thumbnails">
                            <div class="col-md-4 col-xs-4 mix cat_nature cat_all">
                                <a href="https://www.facebook.com/SpurAtTheHubKaren/" class="thumbnail-item">
                                    <img src="{% static 'companies/css/ka/gallery/Burger3.jpg' %}" alt="EaglePeakSpurKaren"/>
                                    <div class="thumbnail-info">

                                    </div>
                                </a>
                                <div class="thumbnail-data">
                                    <h5> Spur At The Hub, Karen.</h5>

                                </div>
                            </div>
                            <div class="col-md-4 col-xs-4 mix cat_space cat_all">
                                <a href="https://www.facebook.com/SpurAtTheHubKaren/" class="thumbnail-item">
                                    <img src="{% static 'companies/css/ka/gallery/T-bone.png' %}" alt="EaglePeakSpurKaren"/>

                                    <div class="thumbnail-info">

                                    </div>
                                </a>
                                <div class="thumbnail-data">
                                    <h5> Spur At The Hub, Karen.</h5>
                                </div>
                            </div>
                            <div class="col-md-4 col-xs-4 mix cat_nature cat_all">
                                <a href="https://www.facebook.com/SpurAtTheHubKaren/" class="thumbnail-item">
                                    <img src="{% static 'companies/css/ka/gallery/Ribs2.jpg' %}" alt="EaglePeakSpurKaren"/>
                                    <div class="thumbnail-info">

                                    </div>
                                </a>
                                <div class="thumbnail-data">
                                    <h5> Spur At The Hub, Karen.</h5>
                                </div>
                            </div>
                        </div>
                         <div class="row mix-grid thumbnails">
                            <div class="col-md-4 col-xs-4 mix cat_music cat_all">
                                <a href="https://www.facebook.com/trbconsultantslimited/" class="thumbnail-item">
                                    <img src="{% static 'companies/css/ka/gallery/Accounting3.jpg' %}" alt="trbconsultantslimited"/>
                                    <div class="thumbnail-info">

                                    </div>
                                </a>
                                <div class="thumbnail-data">
                                    <h5>Trackbook Consultants Ltd.</h5>
                                </div>
                            </div>
                            <div class="col-md-4 col-xs-4 mix cat_nature cat_all">
                                <a href="https://www.facebook.com/trbconsultantslimited/" class="thumbnail-item">
                                    <img src="{% static 'companies/css/ka/gallery/Tax3.jpg' %}" alt="trackBook"/>
                                    <div class="thumbnail-info">

                                    </div>
                                </a>
                                <div class="thumbnail-data">
                                     <h5>Trackbook Consultants Ltd.</h5>
                                </div>
                            </div>
                            <div class="col-md-4 col-xs-4 mix cat_nature cat_all">
                                <a href="https://www.facebook.com/trbconsultantslimited/" class="thumbnail-item">
                                    <img src="{% static 'companies/css/ka/gallery/Book keeping2.jpg' %}" alt="Trackbook"/>
                                    <div class="thumbnail-info">

                                    </div>
                                </a>
                                <div class="thumbnail-data">
                                     <h5>Trackbook Consultants Ltd.</h5>
                                </div>
                            </div>
                         </div>
                         <div class="row mix-grid thumbnails">
                            <div class="col-md-4 col-xs-4 mix cat_music cat_all">
                                <a href="https://www.facebook.com/trbconsultantslimited/" class="thumbnail-item">
                                    <img src="{% static 'companies/css/ka/gallery/Secretarial1.jpg' %}" alt="Trackbook"/>
                                    <div class="thumbnail-info">

                                    </div>
                                </a>
                                <div class="thumbnail-data">
                                     <h5>Trackbook Consultants Ltd.</h5>
                                </div>
                            </div>
                            <div class="col-md-4 col-xs-4 mix cat_nature cat_all">
                                <a href="https://www.facebook.com/trbconsultantslimited/" class="thumbnail-item">
                                    <img src="{% static 'companies/css/ka/gallery/Tax4.jpg' %}" alt="trackBook"/>
                                    <div class="thumbnail-info">

                                    </div>
                                </a>
                                <div class="thumbnail-data">
                                     <h5>Trackbook Consultants Ltd.</h5>
                                </div>
                            </div>
                         </div>

                    </div>
                    <!-- ./page content holder -->
                </div>
                <!-- ./page content wrapper -->
                    <!-- ./page content wrapper -->

                </div>
                <!-- ./page content -->
            {% endblock %}